apiVersion: v1
kind: Pod

metadata:
  name: empty-test

spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "2000"]
    volumeMounts:
    - mountPath: /mnt/nginx-logs
      name: nginx-logs
      readOnly: true
  # this is at the pod level 
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 500Mi