apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0e6883b3bd129b5fa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs
spec:
  storageClassName: "" # means do not use any StorageClass and bind only to a manually created PV.
  volumeName: ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: html-data
        mountPath: /user/share/nginx/template
    volume:
    - name: html-data
      PersistentVolumeClaim:
        claimName: ebs

  