apiVersion: v1
kind: Pod

metadata:
  name: resources-demo
  
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # SOFT LIMIT
      requests:
        memory: "64Mi"    #RAM
        cpu: "100m"       # CPU
      # HARD LIMITS
        limits:
          memory: "128Mi"
          cpu: "150m"

