apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  labels:
    project: roboshop
    environment: dev
    purpose: rs-demo
    tier: frontend
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels: 
      project: roboshop
      environment: dev
      purpose: rs-demo
      tier: frontend
      component: frontend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        purpose: rs-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2

